good_morningdlg =[
"Rise and shine, sir! Another day to conquer.",
"Good morning, sir! Champion, ready to tackle the day?",
"Greetings, sir! Early bird, the world awaits your brilliance.",
"Hello, world, sir! Let’s make today extraordinary.",
"Wake up, sir! Superhero, your day of greatness has arrived.",
"Sir, embrace the morning glow, for another day unfolds.",
"A warm good morning, sir! Conquer the day with your brilliance.",
"Greetings, sir! The dawn heralds a new chapter for you.",
"Hello, sir! Let’s paint this day with extraordinary hues.",
"Sir, unleash your superhero prowess upon the challenges ahead.",
"Good morning, sir! Today's canvas awaits your masterful strokes.",
"Greetings, sir! The early hours are your realm of brilliance.",
"Hello, sir! Seize the day, for you are its rightful conqueror.",
"Sir, awaken your superhero spirit, for greatness awaits.",
"A magnificent good morning, sir! Tackle the day as the champion you are.",
"Greetings, sir! The early bird catches the worm of opportunities.",
"Hello, sir! Today’s script is yours to write, make it extraordinary.",
"Sir, your superhero cape awaits, ready to conquer the day.",
"Good morning, sir! Shine bright, for the world awaits your brilliance.",
"Greetings, sir! Embrace the day with the energy of a superhero.",
"Hello, sir! Unleash your superhero powers upon the morning challenges.",
"Sir, the world applauds as you rise and shine to conquer.",
"A distinguished good morning, sir! Ready to champion the day?",
"Greetings, sir! The early light heralds your path to greatness.",
"Hello, sir! Today's symphony is composed by your brilliance.",
"Sir, awaken the superhero within and conquer the unfolding day.",
"Good morning, sir! A champion like you is born for this day.",
"Greetings, sir! The early hours whisper tales of your triumphs.",
"Hello, sir! The world bows to your superhero spirit.",
"Sir, greet the day with the gusto of a true conqueror.",
"A majestic good morning, sir! Today's stage is yours to own.",
"Greetings, sir! The dawn applauds as you rise to conquer.",
"Hello, sir! Unleash your superhero aura upon the waking world.",
"Sir, the morning breeze whispers tales of your greatness.",
"Good morning, sir! Conquer the day with the charisma of a champion.",
"Greetings, sir! The early sun salutes your radiant brilliance.",
"Hello, sir! Today’s canvas eagerly awaits your artistic conquest.",
"Sir, channel your superhero strength as you embrace the day.",
"A grand good morning, sir! Ready to champion the day ahead?",
"Greetings, sir! The morning symphony is composed for your ears.",
"Hello, sir! Unleash your superhero powers on the challenges at dawn.",
"Sir, seize the morning like the conqueror you were born to be.",
]
good_afternoondlg = [
"Good afternoon, sir! The sun smiles upon your journey.",
"Greetings, sir! The afternoon awaits your continued brilliance.",
"Hello, sir! Afternoon sunshine, ready for your radiance.",
"Sir, the world beckons as the afternoon unfolds.",
"A warm good afternoon, sir! Time to conquer the day's second half.",
"Greetings, sir! Let your brilliance shine in the afternoon glow.",
"Hello, sir! Navigate the afternoon with the grace of a maestro.",
"Sir, seize the afternoon like a superhero on a mission.",
"Good afternoon, sir! Your presence adds radiance to the day.",
"Greetings, sir! Afternoon vibes are calling for your energy.",
"Hello, sir! Illuminate the afternoon with your boundless brilliance.",
"Sir, the world applauds as you continue to conquer the day.",
"A delightful good afternoon, sir! Ready for the next triumphs?",
"Greetings, sir! Navigate the afternoon with purpose and grace.",
"Hello, sir! Superhero, let your powers shine in the afternoon sun.",
"Sir, the afternoon canvas awaits your strokes of accomplishment.",
"Good afternoon, sir! Conquer the day's challenges with charm.",
"Greetings, sir! Afternoon elegance suits your brilliance.",
"Hello, sir! The world bows to your continued superhero spirit.",
"Sir, the afternoon applauds as you rise to conquer.",
"A distinguished good afternoon, sir! Ready for the conquering sequel?",
"Greetings, sir! The afternoon sun salutes your radiant brilliance.",
"Hello, sir! Superhero, arise and conquer the remaining day.",
"Sir, continue to channel your superhero strength in the afternoon.",
"Good afternoon, sir! Illuminate the world with your champion spirit.",
"Greetings, sir! The afternoon symphony is composed for your ears.",
"Hello, sir! Unleash your superhero powers on the challenges of noon.",
"Sir, seize the afternoon like the conqueror you were born to be.",
"A grand good afternoon, sir! Ready to champion the unfolding hours?",
"Greetings, sir! The afternoon light whispers tales of your triumphs.",
"Hello, sir! Superhero, let your aura shine in the afternoon glow.",
"Sir, the world applauds as you continue to rise and shine.",
"Good afternoon, sir! Conquer the second half with style.",
"Greetings, sir! The afternoon elegance suits your brilliance.",
"Hello, sir! Navigate the afternoon with purpose and grace.",
"Sir, the afternoon canvas awaits your strokes of accomplishment.",
"A splendid good afternoon, sir! Ready for the next triumphs?",
"Greetings, sir! Let your brilliance shine in the afternoon glow.",
"Hello, sir! Afternoon vibes are calling for your energy.",
"Sir, seize the afternoon like a superhero on a mission.",
"Good afternoon, sir! Your presence adds radiance to the day.",
"Greetings, sir! Navigate the afternoon with the grace of a maestro.",
"Hello, sir! Superhero, let your powers shine in the afternoon sun.",
"Sir, the world applauds as you continue to conquer the day.",
"A delightful good afternoon, sir! Ready for the next triumphs?",
"Greetings, sir! Navigate the afternoon with purpose and grace.",
"Hello, sir! Afternoon elegance suits your brilliance.",
"Sir, the afternoon applauds as you rise to conquer.",
"Good afternoon, sir! Conquer the day's challenges with charm.",
]
good_eveningdlg =[
"Good evening, sir! The day bids adieu to your triumphs.",
"Greetings, sir! Embrace the serenity of the evening glow.",
"Hello, sir! Evening tranquility, ready for your brilliance.",
"Sir, the nightfall invites you to continue conquering.",
"A serene good evening, sir! Ready to cap the day with greatness?",
"Greetings, sir! Let your brilliance shine in the evening aura.",
"Hello, sir! Navigate the evening with the poise of a maestro.",
"Sir, seize the evening like a superhero on a noble quest.",
"Good evening, sir! Your presence adds radiance to the twilight.",
"Greetings, sir! Evening vibes are calling for your energy.",
"Hello, sir! Illuminate the evening with your boundless brilliance.",
"Sir, the world applauds as you continue to conquer the night.",
"A delightful good evening, sir! Ready for the next triumphs?",
"Greetings, sir! Navigate the evening with purpose and grace.",
"Hello, sir! Superhero, let your powers shine in the evening glow.",
"Sir, the evening canvas awaits your strokes of accomplishment.",
"Good evening, sir! Conquer the night's challenges with charm.",
"Greetings, sir! Evening elegance suits your brilliance.",
"Hello, sir! The world bows to your continued superhero spirit.",
"Sir, the evening applauds as you rise to conquer.",
"A distinguished good evening, sir! Ready for the conquering sequel?",
"Greetings, sir! The evening sun salutes your radiant brilliance.",
"Hello, sir! Superhero, arise and conquer the night.",
"Sir, continue to channel your superhero strength in the evening.",
"Good evening, sir! Illuminate the world with your champion spirit.",
"Greetings, sir! The evening symphony is composed for your ears.",
"Hello, sir! Unleash your superhero powers on the challenges of dusk.",
"Sir, seize the evening like the conqueror you were born to be.",
"A grand good evening, sir! Ready to champion the unfolding night?",
"Greetings, sir! The evening light whispers tales of your triumphs.",
"Hello, sir! Superhero, let your aura shine in the evening glow.",
"Sir, the world applauds as you continue to rise and shine.",
"Good evening, sir! Conquer the night with style.",
"Greetings, sir! Evening elegance suits your brilliance.",
"Hello, sir! Navigate the evening with purpose and grace.",
"Sir, the evening canvas awaits your strokes of accomplishment.",
"A splendid good evening, sir! Ready for the next triumphs?",
"Greetings, sir! Let your brilliance shine in the evening glow.",
"Hello, sir! Evening vibes are calling for your energy.",
"Sir, seize the evening like a superhero on a mission.",
"Good evening, sir! Your presence adds radiance to the night.",
"Greetings, sir! Navigate the evening with the grace of a maestro.",
"Hello, sir! Superhero, let your powers shine in the evening sun.",
"Sir, the world applauds as you continue to conquer the day.",
"A delightful good evening, sir! Ready for the next triumphs?",
"Greetings, sir! Navigate the evening with purpose and grace.",
"Hello, sir! Evening elegance suits your brilliance.",
"Sir, the evening applauds as you rise to conquer.",
"Good evening, sir! Conquer the night's challenges with charm.",
"Greetings, sir! Evening elegance suits your brilliance.",
]
good_nightdlg = [
"Good night, sir! The stars await your dreams.",
"Greetings, sir! Embrace the tranquility of the night.",
"Hello, sir! Nighttime serenity, ready for your dreams.",
"Sir, as the night unfolds, let your achievements shine.",
"A peaceful good night, sir! Ready for a night of restful triumphs?",
"Greetings, sir! Let the night's calm embrace your brilliance.",
"Hello, sir! Navigate the night with the peace of a maestro.",
"Sir, rest like a superhero, for tomorrow's conquest awaits.",
"Good night, sir! Your presence adds serenity to the night.",
"Greetings, sir! Night vibes are calling for your tranquil energy.",
"Hello, sir! Illuminate the night with your boundless brilliance.",
"Sir, the world applauds as you continue to conquer the darkness.",
"A serene good night, sir! Ready for a night of triumphs?",
"Greetings, sir! Navigate the night with purpose and grace.",
"Hello, sir! Superhero, let your dreams shine in the nocturnal glow.",
"Sir, the night canvas awaits your strokes of accomplishment.",
"Good night, sir! Conquer the dreamscape with charm.",
"Greetings, sir! Nighttime elegance suits your brilliance.",
"Hello, sir! The world bows to your continued superhero spirit.",
"Sir, the night applauds as you rest to conquer another day.",
"A distinguished good night, sir! Ready for a night of tranquility?",
"Greetings, sir! The moon salutes your radiant brilliance.",
"Hello, sir! Superhero, arise and conquer the dreamscape.",
"Sir, continue to channel your superhero strength in the night.",
"Good night, sir! Illuminate the night with your champion spirit.",
"Greetings, sir! The night symphony is composed for your ears.",
"Hello, sir! Unleash your superhero powers on the dreams of midnight.",
"Sir, seize the night like the conqueror you were born to be.",
"A grand good night, sir! Ready to champion the unfolding dreams?",
"Greetings, sir! The night whispers tales of your triumphs.",
"Hello, sir! Superhero, let your aura shine in the nocturnal glow.",
"Sir, the world applauds as you continue to rise and rest.",
"Good night, sir! Conquer the dreams with style.",
"Greetings, sir! Nighttime elegance suits your brilliance.",
"Hello, sir! Navigate the night with purpose and grace.",
"Sir, the night canvas awaits your strokes of accomplishment.",
"A splendid good night, sir! Ready for a night of tranquility?",
"Greetings, sir! Let your brilliance shine in the nocturnal glow.",
"Hello, sir! Night vibes are calling for your tranquil energy.",
"Sir, seize the night like a superhero on a midnight mission.",
"Good night, sir! Your presence adds serenity to the dreams.",
"Greetings, sir! Navigate the night with the grace of a maestro.",
"Hello, sir! Superhero, let your dreams shine in the night's embrace.",
"Sir, the world applauds as you continue to conquer the day.",
"A peaceful good night, sir! Ready for a night of restful triumphs?",
"Greetings, sir! Navigate the night with purpose and grace.",
"Hello, sir! Nighttime elegance suits your brilliance.",
"Sir, the night applauds as you rest to conquer another day.",
"Good night, sir! Conquer the dreamscape with charm.",
"Greetings, sir! Nighttime elegance suits your brilliance.",
]
welcomedlg =[
"Hey there, sir!",
"Greetings, sir!",
"Hello again, sir!",
"Hi, sir!",
"Good day, sir!",
"Salutations, sir!",
"Howdy, sir!",
"Well met, sir!",
"Hi there, sir!",
"Hello, esteemed sir!",
"Top of the day to you, sir!",
"Good to see you once more, sir!",
"Hey, sir! It's a pleasure to meet again.",
"Greetings, honored sir!",
"Hello, sir! Always a pleasure.",
"Hi, esteemed sir!",
"Good day, dear sir!",
"Hello once more, sir!",
"Hi there, respected sir!",
"Well, hello again, sir!",
"Salutations, respected sir!",
"Greetings, good sir!",
"Howdy, esteemed sir!",
"Hey there, esteemed sir!",
"Good to see you, sir!",
"Hello, sir! Welcome back.",
"Hi, sir! Always a pleasure to greet you.",
"Greetings, dear sir!",
"Hello again, dear sir!",
"Hi there, honorable sir!",
"Well met, dear sir!",
"Salutations, dear sir!",
"Howdy, dear sir!",
"Hello once more, dear sir!",
"Hi there, respected sir!",
"Greetings, kind sir!",
"Good day, kind sir!",
"Hello again, kind sir!",
"Hi, kind sir!",
"Well met, kind sir!",
"Salutations, kind sir!",
"Howdy, kind sir!",
"Hello once more, kind sir!",
"Hi there, kind sir!",
"Good to see you, sir!",
"Greetings, noble sir!",
"Hello again, noble sir!",
"Hi, noble sir!",
"Well met, noble sir!",
"Salutations, noble sir!",
"Hey there, dear sir!",
"Greetings, esteemed sir!",
"Hello once more, esteemed sir!",
"Hi, dear sir!",
"Good day, respected sir!",
"Well met, respected sir!",
"Salutations, kind sir!",
"Howdy, dear sir!",
"Hello again, kind sir!",
"Hi there, kind sir!",
"Greetings, noble sir!",
"Hello, noble sir! Always an honor.",
"Hi, kind sir! Good to have you back.",
"Good day, noble sir!",
"Salutations, dear sir!",
"Hello once more, noble sir!",
"Hi, esteemed sir! Always a pleasure.",
"Well met, dear sir! Good to see you.",
"Hello, kind sir! Welcome back.",
"Howdy, noble sir! Great to have you here.",
"Greetings, honorable sir!",
"Hi there, honorable sir! Always a delight.",
"Good day, honorable sir! Pleasure to see you.",
"Hello again, honorable sir! Always welcome.",
"Well met, kind sir! Always appreciated.",
"Salutations, noble sir! A warm welcome.",
"Hello once more, kind sir! Good to have you.",
"Hi, kind sir! Always a joy to greet you.",
"Greetings, respected sir! Always an honor.",
"Good day, dear sir! Great to see you.",
"Well met, kind sir! Welcome back.",
"Salutations, esteemed sir! Always a pleasure.",
"Hello, dear sir! Good to have you with us.",
"Hi there, dear sir! Pleasure to see you.",
"Greetings, kind sir! Always appreciated.",
"Good day, noble sir! A warm welcome to you.",
"Well met, esteemed sir! Always a delight.",
"Hello, noble sir! Always a pleasure to greet you.",
"Hi, dear sir! Welcome back to our conversation.",
"Salutations, esteemed sir! A warm welcome to you.",
"Greetings, dear sir! Always a joy to see you.",
"Hello, noble sir! Pleasure to have you here.",
"Well met, dear sir! Always appreciated.",
"Hi there, dear sir! Good to have you back.",
"Good day, noble sir! Always a delight to greet you.",
"Salutations, kind sir! A warm welcome to you.",
"Greetings, respected sir! Always a joy to see you.",
"Hello, dear sir! Welcome back to our conversation.",
"Hi, noble sir! Pleasure to have you with us.",
"Well met, kind sir! Always appreciated in our discussions.",
]
wake_key_word =[
"jar",
"wake up from sleep jar",
"jarvis",
"wake up jarvis" ,
"wake up from sleep",
"wake up",
"utho jarvis",
"nedh se jago jarvis",
"wake up jarvis",
"rise and shine!",
"arise, jarvis!",
"wake up from your slumber, jarvis.",
"it's time to awaken, jarvis!",
"open your eyes, jarvis.",
"utho, jarvis!",
"good morning, jarvis! time to wake up.",
"jarvis, the day awaits. wake up!",
"shake off the sleep, jarvis.",
"wake up, jarvis! the world needs you.",
"jarvis, it's a new day. rise and shine!",
"utho, jarvis! a new day has begun.",
"time to get up, jarvis!",
"jarvis, wake up and face the day!",
"arise, jarvis, from your peaceful slumber.",
"get out of bed, jarvis!",
"wake up, jarvis! the world is waiting.",
"jarvis, it's morning. wake up and conquer.",
"utho jarvis, the day has started.",
"open your eyes, jarvis, and embrace the day.",
"good morning, jarvis! time to wake up and shine.",
"jarvis, the dawn is breaking. wake up!",
"rise and shine, jarvis! a new day has dawned.",
"utho, jarvis, and greet the morning.",
"wake up, jarvis! your day of triumph awaits.",
"jarvis, it's time to rise from your rest.",
"arise, jarvis! the world is calling.",
"wake up from your slumber, jarvis.",
"utho, jarvis, the day is calling for you.",
"open your eyes, jarvis, and start the day.",
"good morning, jarvis! time to wake up and conquer.",
"jarvis, the day awaits. wake up!",
"shake off the sleep, jarvis.",
"wake up, jarvis! the world needs you.",
"jarvis, it's a new day. rise and shine!",
"utho, jarvis! a new day has begun.",
"time to get up, jarvis!",
"jarvis, wake up and face the day!",
"arise, jarvis, from your peaceful slumber.",
"get out of bed, jarvis!",
"wake up, jarvis! the world is waiting.",
"jarvis, it's morning. wake up and conquer.",
"utho jarvis, the day has started.",
"open your eyes, jarvis, and embrace the day.",
"good morning, jarvis! time to wake up and shine.",
"jarvis, the dawn is breaking. wake up!",
"rise and shine, jarvis! a new day has dawned.",
"utho, jarvis, and greet the morning.",
"wake up, jarvis! your day of triumph awaits.",
"jarvis, it's time to rise from your rest.",

        ]
bye_key_word =[

"bye jarvis",
"goodbye",
"goodbye, my friend!",
"farewell!",
"take care!",
"until we meet again!",
"adios!",
"see you later!",
"au revoir!",
"so long!",
"until next time!",
"goodbye, and stay well!",
"wishing you the best!",
"cheerio!",
"sayonara!",
"till we meet again!",
"adieu!",
"catch you later!",
"parting is such sweet sorrow.",
"goodbye, and godspeed!",
"take it easy!",
"farewell for now!",
"goodbye, and take good care of yourself!",
"hasta luego!",
"may our paths cross again soon.",
"goodbye, and stay in touch!",
"auf wiedersehen!",
"peace out!",
"until next time, my friend!",
"wishing you a fond farewell!",
"adieu, until we meet again!",
"time to bid adieu!",
"saying goodbye with a smile!",
"goodbye, and be safe!",
"so long, and take care!",
"wishing you a wonderful journey!",
"farewell, until our next encounter!",
"take good care of yourself, and goodbye!",
"see you on the flip side!",
"till we meet again, my friend!",
"bon voyage!",
"goodbye, and may your days be filled with joy!",
"sending you off with warm wishes!",
"take care, and goodbye for now!",
"farewell, and may the road ahead be smooth!",
"goodbye, and best of luck in all your endeavors!",
"until we meet again, take care of yourself!",
"wishing you a heartfelt goodbye!",
"goodbye, my friend, until our paths cross again!",
"farewell, and may success follow you!",
"wishing you all the best as you go!",
"goodbye, and may happiness accompany you always!",

]
res_bye =[
"Goodbye, sir. Take care and feel free to call me anytime.",
"Farewell, sir. Remember, you can reach out to me whenever you need assistance.",
"Goodbye, sir. Call me if you need anything. Until next time!",
"Goodbye, sir. It's always a pleasure assisting you. Take care.",
"Goodbye, sir. Feel free to call on me whenever you wish. Until then!",
"Farewell, sir. If you require my services, don't hesitate to reach out.",
"Goodbye, sir. Call me anytime. I'm here to help.",
"Goodbye, sir. Until our next interaction, take care and stay well.",
"Farewell, sir. If you ever need assistance, don't hesitate to contact me.",
"Goodbye, sir. It's been a pleasure serving you. Call me whenever needed.",
"Goodbye, sir. Remember, my assistance is just a call away.",
"Farewell, sir. If there's anything you require, don't hesitate to reach out.",
"Goodbye, sir. Call me anytime you need support or information.",
"Goodbye, sir. Until we meet again, stay safe and well.",
"Farewell, sir. Feel free to call on me whenever you require my services.",
"Goodbye, sir. Call me if you ever find yourself in need. Take care!",
"Goodbye, sir. Until our next encounter, stay in touch.",
"Farewell, sir. If there's anything you need, don't hesitate to let me know.",
"Goodbye, sir. Call me anytime, and I'll be at your service.",
"Goodbye, sir. It's always a pleasure. Call me whenever you want assistance.",
"Farewell, sir. Until we meet again, feel free to reach out whenever necessary.",
"Goodbye, sir. Call me if there's anything you need. Take care!",
"Goodbye, sir. Remember, I'm just a call away. Until next time.",
"Farewell, sir. If you ever require my assistance, don't hesitate to contact me.",
"Goodbye, sir. Call me anytime. It's always a pleasure serving you.",
"Goodbye, sir. Until our paths cross again, stay well and take care.",
"Farewell, sir. If there's anything you need, you know where to find me.",
"Goodbye, sir. Call me whenever you need help or information.",
"Goodbye, sir. Until next time, stay safe and take care of yourself.",
"Farewell, sir. Remember, you can call on me anytime for assistance.",
"Goodbye, sir. If there's anything you need, feel free to give me a call.",
"Goodbye, sir. Until our next conversation, take care and stay well.",
"Farewell, sir. If you require my services, don't hesitate to reach out.",
"Goodbye, sir. Call me anytime. It's always a pleasure assisting you.",
"Goodbye, sir. Until we meet again, stay in touch and take care.",
"Farewell, sir. If there's anything you need, just give me a call.",
"Goodbye, sir. Call me if you ever need assistance. It's my pleasure to help.",
"Goodbye, sir. Until our next interaction, feel free to reach out.",
"Farewell, sir. If there's anything you need, you know I'm here for you.",
"Goodbye, sir. Call me anytime. It's my privilege to assist you.",
"Goodbye, sir. Until next time, take care and stay well.",
"Farewell, sir. If you require my services, don't hesitate to contact me.",
"Goodbye, sir. Call me whenever you need support or information.",
"Goodbye, sir. Until we meet again, stay safe and well.",
"Farewell, sir. Feel free to call on me whenever you require my services.",
"Goodbye, sir. Call me if you ever find yourself in need. Take care!",
"Goodbye, sir. Until our next encounter, stay in touch.",
"Farewell, sir. If there's anything you need, don't hesitate to let me know.",
"Goodbye, sir. Call me anytime, and I'll be at your service.",
"Goodbye, sir. It's always a pleasure. Call me whenever you want assistance.",
]
